### ISSUE TITLE
Setup Database

### ISSUE THREAD

**Issue by lukaswolfrum** [Calcoph/ai-slide-talk#4]
- Integrate Database (is a relational DB working? We need to store pdfs?)
	Login:
	- User Credentials (username, pw, OPENAI API KEY)
	- User Chat History (per Lecture)
			
	Lectures:
	- Lecture Vectors
	- PDFs?
	- Chats
	
	Chat:
	- User Chat History (per Lecture)

**Comment by lukaswolfrum** [comment]
There is a streamlit tuorial for connecting streamlit with different dbs, here is the one for mysql: 
https://docs.streamlit.io/knowledge-base/tutorials/databases/mysql

https://docs.streamlit.io/knowledge-base/tutorials/databases

**Comment by un4rch** [comment]
Database tasks:

- [x]  Mysql connection
- [x] Create tables
- [x] adapt old database system to new mysql

**Comment by lukaswolfrum** [comment]
- [x] Database for Vectors
- [x] Database for pdfs
